---
title: "Fifa World Cup Data Wrangling"
format: gfm
jupyter: python3
---


```{python}

import pandas as pd 
import statsmodels.api as sm
import seaborn as sns
import re
import matplotlib.pyplot as plt
import statsmodels.formula.api as smf
import numpy as np

```



```{python}
data = pd.read_csv('~/Documents/Data_Wrangling/Fifa_world_cup_matches.csv')

data.columns

data.info

data.info(verbose=True)

```



```{python}
pd.set_option('display.max_columns', None)
data.head()
data.columns

data.head()
data2 = pd.read_csv('~/Documents/Data_Wrangling/fifa_mens_rank.csv')

data2.columns

data2.head()
```


Below I am cleaning the possession columns to be integers instead of strings with % signs.
```{python}
data['possession team1'] = data['possession team1'].str.replace('%','', regex=False).astype(int)
data['possession team2'] = data['possession team2'].str.replace('%','', regex=False).astype(int)
data['possession in contest'] = data['possession in contest'].str.replace('%','', regex=False).astype(int)

data.groupby(['team1', 'team2']).agg({'possession team1':['mean'], 'possession team2': ['mean']})

```


Below I am seprating the data into seperate dataframes for team1 and team2.
```{python}
Team1_col = [col for col in data if (re.search(r'team1',col )) or (col in ['date', 'hour', 'category'])]

Team1_col

Team1_data = data[Team1_col]

Team1_data['team1'] = Team1_data['team1'].str.title()

Team1_data

Team2_col = [col for col in data if (re.search(r'team2',col )) or (col in ['date', 'hour', 'category'])]

Team2_col

Team2_data = data[Team2_col]

Team2_data

Team2_data['team2'] = Team2_data['team2'].str.title()

Team2_data

```



Below I am converting the integer columns to mean stats for both dataframes
```{python}
int_cols_1 = Team1_data.select_dtypes(include = 'int64').columns

team1_mean_stats = Team1_data.groupby('team1', as_index=False)[int_cols_1].mean()

team1_mean_stats = team1_mean_stats.round(2)

team1_mean_stats

int_cols_2 = Team2_data.select_dtypes(include = 'int64').columns

team2_mean_stats = Team2_data.groupby('team2', as_index=False)[int_cols_2].mean()

team2_mean_stats = team2_mean_stats.round(2)

print(team2_mean_stats)

```


Just cleaning up the column names for merging later
```{python}
team1_mean_stats = team1_mean_stats.rename(columns = lambda s: s.replace('team1', 'Team'))

print(team1_mean_stats)

team1_mean_stats.columns = team1_mean_stats.columns.str.replace(' Team','', regex=False)

print(team1_mean_stats)

team2_mean_stats = team2_mean_stats.rename(columns = lambda s: s.replace('team2', 'Team'))

team2_mean_stats.columns = team2_mean_stats.columns.str.replace(' Team','', regex=False)

print(team2_mean_stats)
```


Finally merging both dataframes and averaging the stats for teams that played as both team1 and team2
```{python}
merge = pd.concat([team1_mean_stats, team2_mean_stats], axis=0).reset_index(drop=True)
combined = merge.groupby('Team').mean()

print(combined)

data2['date'] = data2['date'].astype(str)

data2.dtypes

data2 = data2[data2['date'] == '2022']

data2 

data2.columns = data2.columns.str.title()

combined.columns = combined.columns.str.title()

combined

Fifa = pd.merge(combined, data2, how = 'left', left_on = 'Team', right_on = 'Team')
```

I am dropping duplicates teams and adding a region column for later analysis. Additionally I am adding in missing rank and total points for teams that don't have them.

```{python}

Fifa.head()

Clean_fifa = Fifa.drop_duplicates(subset=['Team'])
Clean_fifa = Clean_fifa.reset_index(drop=True)
print(Clean_fifa)

Clean_fifa.head(32)


fifa_region_map = {
    'Qatar': 'AFC',
    'Iran': 'AFC',
    'Saudi Arabia': 'AFC',
    'Japan': 'AFC',
    'Korea Republic': 'AFC',
    'Australia': 'AFC',
    'Senegal': 'CAF',
    'Tunisia': 'CAF',
    'Morocco': 'CAF',
    'Cameroon': 'CAF',
    'Ghana': 'CAF',
    'United States': 'CONCACAF',
    'Mexico': 'CONCACAF',
    'Canada': 'CONCACAF',
    'Costa Rica': 'CONCACAF',
    'Argentina': 'CONMEBOL',
    'Brazil': 'CONMEBOL',
    'Uruguay': 'CONMEBOL',
    'Ecuador': 'CONMEBOL',
    'Belgium': 'UEFA',
    'Denmark': 'UEFA',
    'England': 'UEFA',
    'France': 'UEFA',
    'Germany': 'UEFA',
    'Netherlands': 'UEFA',
    'Poland': 'UEFA',
    'Portugal': 'UEFA',
    'Spain': 'UEFA',
    'Switzerland': 'UEFA',
    'Croatia': 'UEFA',
    'Wales': 'UEFA',
    'Serbia': 'UEFA'
}

Clean_fifa['Region'] = Clean_fifa['Team'].map(fifa_region_map)

Clean_fifa.loc[Clean_fifa['Team'] == 'United States', 'Rank'] = 16
Clean_fifa.loc[Clean_fifa['Team'] == 'Iran', 'Rank'] = 20

Clean_fifa.loc[Clean_fifa['Team'] == 'United States', 'Total.Points'] = 1627
Clean_fifa.columns = Clean_fifa.columns.str.replace(" ", "_")
```



Now that we cleaned the data. 


Does the fifa ranking have any correlation with style of play?

Run a model with Rank as dependent variable and style of play stats as independent variables. 

Like Possession, Passes Completed, Passes Attempted, Pass Accuracy, Shots on Target, Shots off Target, Fouls Committed, Fouls Suffered, Yellow Cards, Red Cards.

```{python}

y= Clean_fifa['Rank']
x = sm.add_constant(Clean_fifa[['Possession', 'Total_Attempts', 'Attempts_Inside_The_Penalty_Area', 'Yellow_Cards', 'Red_Cards', 'Fouls_Against', 'Passes']])

fit_1 = smf.ols(formula = 'Rank ~ Possession + Total_Attempts + Yellow_Cards + Red_Cards', data = Clean_fifa).fit()
fit_1.summary()
```

Poession doesn't have any sort of significant correlation with the fifa ranking. 


What does it say about goals, conceded goals and assists?
```{python}

fit_2 = smf.ols(formula = 'Rank ~ Number_Of_Goals + Conceded + Assists', data = Clean_fifa).fit()
fit_2.summary()

```

Shows that number of goals and conceded have a significant correlation with fifa ranking. Assists don't but that can be due to number of things like penalties being counted as goals but not assists.


What does this look like visually?

```{python}

plt.scatter(Clean_fifa['Number_Of_Goals'], Clean_fifa['Rank'])
plt.figure(figsize=(10,6))
plt.show()



plt.scatter(Clean_fifa['Conceded'], Clean_fifa['Rank'])
plt.figure(figsize=(10,6))
plt.show()
```


What happens when we Subset and filter stats? What kind of teams do we have?

Subet and Filter by possession
```{python}

High_Possesion  =Clean_fifa[(Clean_fifa['Possession']>=  55)]

Mid_Possesion = Clean_fifa[(Clean_fifa['Possession'] <=  54) & (Clean_fifa['Possession'] >= 49)]

Mid_to_Low_Possesion = Clean_fifa[(Clean_fifa['Possession'] <= 48) & (Clean_fifa['Possession'] >= 40)]
Mid_to_Low_Possesion

Low_Possesion = Clean_fifa[(Clean_fifa['Possession']< 40)]
Low_Possesion

```

What do the rankings look like for these different possession styles?

```{python}

High_Possesion.nsmallest(3, 'Rank')[['Team', 'Rank', 'Possession']]

Mid_Possesion.nsmallest(3, 'Rank')[['Team', 'Rank', 'Possession']]

Mid_to_Low_Possesion.nsmallest(3, 'Rank')[['Team', 'Rank', 'Possession']]

Low_Possesion.nsmallest(3, 'Rank')[['Team', 'Rank', 'Possession']]

```

This reiterates the regression results that possession doesn't have a significant correlation with fifa ranking.


 Subet and Filter  by Goals

```{python}


High_Number_Goals = Clean_fifa[(Clean_fifa['Number_Of_Goals'] >=  2)]
High_Number_Goals

Mid_Number_Goals = Clean_fifa[(Clean_fifa['Number_Of_Goals'] <=  1.9) & (Clean_fifa['Number_Of_Goals'] >=1)]
Mid_Number_Goals

Low_Number_Goals = Clean_fifa[(Clean_fifa['Number_Of_Goals']< 1)]
Low_Number_Goals
```

What do the ranks look here

```{python}

High_Number_Goals.nsmallest(3, 'Rank')[['Team', 'Rank', 'Number_Of_Goals']]

Mid_Number_Goals.nsmallest(3, 'Rank')[['Team', 'Rank', 'Number_Of_Goals']]

Low_Number_Goals.nsmallest(3, 'Rank')[['Team', 'Rank', 'Number_Of_Goals']]

```



Subet and Filter by conceded goals
```{python}

Good_defense = Clean_fifa[(Clean_fifa['Conceded'] <=  0.5)]
Good_defense

Mid_defense = Clean_fifa[(Clean_fifa['Conceded'] >=  0.51) & (Clean_fifa['Conceded'] <=1)]
Mid_defense

Mid_to_Terrible_defense = Clean_fifa[(Clean_fifa['Conceded'] >=  1.1) & (Clean_fifa['Conceded'] <= 2)]
Mid_to_Terrible_defense

Terrible_defense = Clean_fifa[(Clean_fifa['Conceded'] >= 2.1)]
Terrible_defense

```

```{python}

Good_defense.nsmallest(3, 'Rank')[['Team', 'Rank', 'Conceded']]

Mid_defense.nsmallest(3, 'Rank')[['Team', 'Rank', 'Conceded']]

Mid_to_Terrible_defense.nsmallest(3, 'Rank')[['Team', 'Rank', 'Conceded']]

Terrible_defense.nsmallest(3, 'Rank')[['Team', 'Rank', 'Conceded']]


```

Subset and Filter by fouls against

What kind of teams do we have? What regions? Graphically how does each agression level look like by region?

```{python}

Passive_Teams = Clean_fifa[(Clean_fifa['Fouls_Against'] <=  10)]

Balanced_Teams = Clean_fifa[(Clean_fifa['Fouls_Against'] > 10) &(Clean_fifa['Fouls_Against'] <= 13)]

Aggressive_Teams = Clean_fifa[(Clean_fifa['Fouls_Against'] > 13)]

```

```{python}

Passive_Teams_count = Passive_Teams['Region'].value_counts()

plt.bar(Passive_Teams_count.index, Passive_Teams_count.values)
plt.show()



Balanced_Teams_count = Balanced_Teams['Region'].value_counts()

plt.bar(Balanced_Teams_count.index, Balanced_Teams_count.values)
plt.show()



Aggressive_Teams_count = Aggressive_Teams['Region'].value_counts()

plt.bar(Aggressive_Teams_count.index, Aggressive_Teams_count.values)
plt.show()

```



